from typing import *

# project types

PROJECT_TYPE_SCRATCH: int = 0
PROJECT_TYPE_PYTHON: int = 1
PROJECT_TYPE_UNITY: int = 2
PROJECT_TYPE_GODOT: int = 3
PROJECT_TYPE_ROBLOX: int = 4
PROJECT_TYPE_LINK: int = 5
PROJECT_TYPE_PRESENTATION: int = 6
PROJECT_TYPE_IMAGE: int = 7
PROJECT_TYPE_BLENDER: int = 8
PROJECT_TYPE_SITE: int = 9

# access types

ACCESS_TYPE_PRIVATE: int = 0
ACCESS_TYPE_PUBLIC: int = 9
ACCESS_TYPE_SCHOOL: int = 1